language: ruby
os: linux
rvm:
  - 2.6
  - 2.7
gemfile:
  - spec/gemfiles/rails_5_0.gemfile
  - spec/gemfiles/rails_5_2.gemfile
git:
  submodules: false
env:
  global:
  - TRAVIS=1
jobs:
  allow_failures:
  - rvm: rbx-3
  exclude:
  - rvm: jruby-9
    gemfile: spec/gemfiles/rails_4_2.gemfile
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

script:
- >
  if [[ "$(rvm current)" = "ruby-"* ]]; then
    COVERAGE=1 bundle exec rspec --format d
  else
    bundle exec rspec --format d
  fi
- >
  if [[ "$(rvm current)" = "ruby-"* ]]; then
    bundle exec codeclimate-test-reporter
  fi
